apiVersion: v1
kind: Service
metadata:
  name: kubepulse-service
spec:
  type: NodePort

  selector:
    app: kubepulse

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30090
