apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepulse-sa
  namespace: production

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepulse-role

rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
  verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepulse-binding

subjects:
- kind: ServiceAccount
  name: kubepulse-sa
  namespace: production

roleRef:
  kind: ClusterRole
  name: kubepulse-role
  apiGroup: rbac.authorization.k8s.io