name: KubePulse CI/CD Pipeline
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install flake8
        run: pip install flake8

      - name: Run Lint
        run: flake8 app/

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        env:
          ENV: test
        run: |
           PYTHONPATH=. pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t kubepulse-lite:${{ github.sha }} .

  security-scan:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image for scan
        run: |
          docker build -t kubepulse-lite:${{ github.sha }} .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: kubepulse-lite:${{ github.sha }}

  docker-push:
   needs: security-scan
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      run: |
       echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Image
      run: |
       docker build -t ${{ secrets.DOCKER_USER }}/kubepulse-lite:${{ github.sha }} .

    - name: Push Image
      run: |
       docker push ${{ secrets.DOCKER_USER }}/kubepulse-lite:${{ github.sha }}

    - name: Setup kubeconfig
      run: |
       mkdir -p $HOME/.kube
       printf '%s' '${{ secrets.KUBECONFIG_BASE64 }}' | base64 -d > $HOME/.kube/config

    - name: Verify kubeconfig
      run: |
       kubectl config view
       kubectl get ns