name: KubePulse CI-CD

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - run: |
        pip install flake8
        flake8 app/

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - run: |
        pip install -r app/requirements.txt
        pip install pytest

    - run: |
        pytest

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t kubepulse-lite:${{ github.sha }} .

  security-scan:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: kubepulse-lite:${{ github.sha }}

  docker-push:
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Image
      run: |
        docker build -t your-dockerhub/kubepulse-lite:${{ github.sha }} .

    - name: Push Image
      run: |
        docker push your-dockerhub/kubepulse-lite:${{ github.sha }}

  deploy-staging:
    needs: docker-push
    runs-on: ubuntu-latest
    environment: staging
